apiVersion: apps/v1
kind: Deployment
metadata:
  name: dress-fy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dress-fy-api
  template:
    metadata:
      labels:
        app: dress-fy-api
    spec:
      imagePullSecrets:
        - name: regcred   
      containers:
        - name: dress-fy-api
          image: altenirm/dress-fy-api:latest
          ports:
            - containerPort: 8000   
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: dress-fy-api
spec:
  type: NodePort
  selector:
    app: dress-fy-api
  ports:
    - port: 80
      targetPort: 8000  