apiVersion: v1
kind: ConfigMap
metadata:
  name: csdressfy-mysql-config
data:
  MYSQL_ROOT_PASSWORD: "root_password"
  MYSQL_USER: "deteccao_user"  
  MYSQL_PASSWORD: "user_password"        
  MYSQL_DATABASE: "deteccao_db"
